## Name: Gopani Kenil G. 
## Roll No: CE049 
## ID: 19CEUOS080
##  Lab-5

### Task 1: 
#### Try the algo on Same Weather dataset - LabelEncoding of features: and Train test Division 80%-20% with Gini Index as attribute selection measure

In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier

In [2]:
#Predictor variables
Outlook = ['Rainy', 'Rainy', 'Overcast', 'Sunny', 'Sunny', 'Sunny','Overcast',
           'Rainy', 'Rainy', 'Sunny', 'Rainy','Overcast', 'Overcast','Sunny']
Temperature = ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool',
               'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild']
Humidity = ['High', 'High', 'High', 'High', 'Normal', 'Normal', 'Normal',
            'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal','High']
Wind = ['False', 'True', 'False', 'False', 'False', 'True', 'True',
        'False', 'False', 'False', 'True', 'True', 'False', 'True']

#Class Label:
Play = ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No',
        'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']

### Label Encoding

In [3]:
#creating labelEncoder
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
Outlook_encoded = le.fit_transform(Outlook)
Outlook_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print("Outllok mapping:",Outlook_name_mapping)

Temperature_encoded = le.fit_transform(Temperature)
Temperature_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print("Temperature mapping:",Temperature_name_mapping)

Humidity_encoded = le.fit_transform(Humidity)
Humidity_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print("Humidity mapping:",Humidity_name_mapping)

Wind_encoded = le.fit_transform(Wind)
Wind_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print("Wind mapping:",Wind_name_mapping)

Play_encoded = le.fit_transform(Play)
Play_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print("Play mapping:",Play_name_mapping)

print("\n\n")
print("Weather:" ,Outlook_encoded)
print("Temerature:" ,Temperature_encoded)
print("Humidity:" ,Humidity_encoded)
print("Wind:" ,Wind_encoded)
print("Play:" ,Play_encoded)

Outllok mapping: {'Overcast': 0, 'Rainy': 1, 'Sunny': 2}
Temperature mapping: {'Cool': 0, 'Hot': 1, 'Mild': 2}
Humidity mapping: {'High': 0, 'Normal': 1}
Wind mapping: {'False': 0, 'True': 1}
Play mapping: {'No': 0, 'Yes': 1}



Weather: [1 1 0 2 2 2 0 1 1 2 1 0 0 2]
Temerature: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Humidity: [0 0 0 0 1 1 1 0 1 1 1 0 1 0]
Wind: [0 1 0 0 0 1 1 0 0 0 1 1 0 1]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


### Merge different features to prepare dataset

In [4]:
attr = {'Outlook':Outlook_encoded, 'Temperature':Temperature_encoded, 'Humidity':Humidity_encoded,
            'Wind':Wind_encoded, 'Play':Play_encoded}
dataset = pd.DataFrame(attr)
dataset

Outlook  Temperature  Humidity  Wind  Play
0         1            1         0     0     0
1         1            1         0     1     0
2         0            1         0     0     1
3         2            2         0     0     1
4         2            0         1     0     1
5         2            0         1     1     0
6         0            0         1     1     1
7         1            2         0     0     0
8         1            0         1     0     1
9         2            2         1     0     1
10        1            2         1     1     1
11        0            2         0     1     1
12        0            1         1     0     1
13        2            2         0     1     0

### Spliting dataset

In [5]:
from sklearn.model_selection import train_test_split

X = dataset.values[:,:-1]
Y = dataset.values[:,-1:]

# Train test Division 80%-20%
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 49)

### Train ’Create and Train DecisionTreeClassifier’

In [6]:
classifier = DecisionTreeClassifier(criterion = "gini", random_state = 49, max_depth=49, min_samples_leaf=5)

classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=49, min_samples_leaf=5, random_state=49)

In [7]:
# make prediction
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 1], dtype=int64)

In [8]:
from sklearn import metrics

# Accuracy
accuracy = metrics.accuracy_score(y_test,y_pred)
print('Accuracy : ',accuracy)

# Precision
precision = metrics.precision_score(y_test,y_pred)
print('Precision : ',precision)

# Recall
recall = metrics.recall_score(y_test,y_pred)
print('Recall : ',recall)

Accuracy :  0.6666666666666666
Precision :  1.0
Recall :  0.5


### Predict output for new data

In [9]:
# What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?

classifier.predict([[1,2,1,0]])

array([1], dtype=int64)

In [10]:
# What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity=’High’, and Wind = ’True’?

classifier.predict([[2,0,0,1]])

array([0], dtype=int64)