## Name: Gopani Kenil G. 
## Roll No: CE049 
## ID: 19CEUOS080
##  Lab-5

### Task 2: 
### Apply algorithm on digits dataset - One Hot Encoding of features: and Train test Division 65%-35%

In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier

In [2]:
# load dataset
from sklearn.datasets import load_digits
digits = load_digits(as_frame=True)

In [3]:
digits.data.shape

(1797, 64)

In [4]:
digits.frame

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        0.0        0.0   
3           0.0        0.0        0.0        8.0  ...        0.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        0.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        0.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        0.0        0.0   

      pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0           0.0        6.0       13.0       10.0        0.0        0.0   
1           0.0        0.0       11.0       16.0       10.0        0.0   
2           0.0        0.0        3.0       11.0       16.0        9.0   
3           0.0        7.0       13.0       13.0        9.0        0.0   
4           0.0        0.0        2.0       16.0        4.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        2.0       14.0       15.0        9.0        0.0   
1793        0.0        6.0       16.0       14.0        6.0        0.0   
1794        0.0        2.0        9.0       13.0        6.0        0.0   
1795        0.0        5.0       12.0       16.0       12.0        0.0   
1796        1.0        8.0       12.0       14.0       12.0        1.0   

      pixel_7_7  target  
0           0.0       0  
1           0.0       1  
2           0.0       2  
3           0.0       3  
4           0.0       4  
...         ...     ...  
1792        0.0       9  
1793        0.0       0  
1794        0.0       8  
1795        0.0       9  
1796        0.0       8  

[1797 rows x 65 columns]

### One-Hot Encoding

In [5]:
# one-hot encoder
ohe = preprocessing.OneHotEncoder()

encoded_dataset = ohe.fit_transform(digits.frame).toarray()

print('shape of encoded dataset :')
print(encoded_dataset.shape)
print()
print('Encoded Dataset :')
print(encoded_dataset)

shape of encoded dataset :
(1797, 900)

Encoded Dataset :
[[1. 1. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 1. 0.]
 [1. 1. 0. ... 0. 0. 1.]
 [1. 1. 0. ... 0. 1. 0.]]


In [6]:
data = pd.DataFrame(encoded_dataset)
data

0    1    2    3    4    5    6    7    8    9    ...  890  891  892  \
0     1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
1     1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
2     1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
3     1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4     1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1792  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1793  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
1794  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1795  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1796  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      893  894  895  896  897  898  899  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3     1.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  1.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
1792  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
1793  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1794  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
1795  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
1796  0.0  0.0  0.0  0.0  0.0  1.0  0.0  

[1797 rows x 900 columns]

### Spliting dataset

In [7]:
from sklearn.model_selection import train_test_split

X = data.values[:,:-10]
Y = data.values[:,-10:]

# Train test Division 80%-20%
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.35, random_state = 49)

### Train ’Create and Train DecisionTreeClassifier’

In [8]:
classifier = DecisionTreeClassifier(criterion = "gini", random_state = 49, max_depth=49, min_samples_leaf=5)

classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=49, min_samples_leaf=5, random_state=49)

In [9]:
# make prediction
y_pred = classifier.predict(X_test)
y_pred

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [10]:
y_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [11]:
from sklearn import metrics

# Accuracy
accuracy = metrics.accuracy_score(y_test,y_pred)
print('Accuracy : ',accuracy)

# Precision
precision = metrics.precision_score(y_test,y_pred, average=None)
print('Precision : ',precision)

# Recall
recall = metrics.recall_score(y_test,y_pred, average=None)
print('Recall : ',recall)

Accuracy :  0.7742448330683624
Precision :  [0.90384615 0.77777778 0.80952381 0.71666667 0.96363636 0.82142857
 0.84057971 0.90625    0.59677419 0.83333333]
Recall :  [0.92156863 0.65333333 0.67105263 0.7962963  0.79104478 0.82142857
 0.86567164 0.92063492 0.61666667 0.75      ]
