Name: Gopani Kenil G.
Roll No: CE049
ID: 19CEUOS080
@numpy

In [1]:
import numpy as np
from numpy import random
import pandas as ps

In [19]:
array1 = np.array([[1,-9,8,0,12],[8,9,1,2,4],[5,-6,2,4,9],[7,-7,6,-6,1]])
print(array1)

[[ 1 -9  8  0 12]
 [ 8  9  1  2  4]
 [ 5 -6  2  4  9]
 [ 7 -7  6 -6  1]]


2) Randomly initialize the array.

In [3]:
rand_array = random.randint(100,size=10)
print(rand_array)

[73  4 22 77 94 19 84 92 63 33]


3) Get the Transpose of the Matrix that you created. Create a square matrix and find its determinant.

In [4]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]]);
transpose_matrix = matrix.T
print(transpose_matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


4) Create another matrix of size 5 x 4 and randomly initialize it.

In [5]:
rand_matrix = random.randint(99,size=(5,4))
print(rand_matrix)

[[77 68 54 17]
 [89 12 65 25]
 [35 45 88 79]
 [67 37 93 93]
 [28 12 27 65]]


5) Perform Matrix multiplication.

In [6]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[2,1],[4,3]])
result = np.dot(matrix1,matrix2)
print(result)

[[10  7]
 [22 15]]


6) Perform element wise matrix multiplication.

In [8]:
matrix1 = np.array([[1,0],[3,-4]])
matrix2 = np.array([[-2,1],[2,3]])
result = matrix1 * matrix2
print(result)

[[ -2   0]
 [  6 -12]]


7) Find mean, median of the numpy array created.

In [9]:
arr = np.array([6,3,4,5,2,8])
mean = np.mean(arr)
median = np.median(arr)
print("mean is = " ,mean)
print("median is = ",median)

mean is =  4.666666666666667
median is =  4.5


8) Obtain each row in the second column of the first array.

In [27]:
print(array1)
print(array1[0:,1])

[[ 1 -9  8  0 12]
 [ 8  9  1  2  4]
 [ 5 -6  2  4  9]
 [ 7 -7  6 -6  1]]
[-9  9 -6 -7]


9) Convert Numeric entries(columns) of Iris.csv to Mean Centered Version

In [16]:
data = ps.read_csv('./Iris.csv')
#print(data.to_string()) /////    tp print all data of .csv file.
print("Mean of SepalLengthCm",np.mean(data['SepalLengthCm']),sep=" :- ",end='\n')
print("Mean of SepalWidthCm",np.mean(data['SepalWidthCm']),sep=" :- ",end='\n')
print("Mean of PetalLengthCm",np.mean(data['PetalLengthCm']),sep=" :- ",end='\n')
print("Mean of PetalWidthCm",np.mean(data['PetalWidthCm']),sep=" :- ",end='\n')

Mean of SepalLengthCm :- 5.843333333333334
Mean of SepalWidthCm :- 3.0540000000000003
Mean of PetalLengthCm :- 3.758666666666666
Mean of PetalWidthCm :- 1.1986666666666668


10) Study about numpy array attributes and implement it on the first matrix.

In [10]:
print(array1)
print()
print("Dimention of array1 is:- ",array1.ndim)
print("Shap of array1 is:- ",array1.shape)
print("Data type of array1 is:- ",array1.dtype)
print("Total size of array1 is:- ",array1.size)
print("Sizeof each element of array1 is:- ",array1.itemsize)

[[ 1 -9  8  0 12]
 [ 8  9  1  2  4]
 [ 5 -6  2  4  9]
 [ 7 -7  6 -6  1]]

Dimention of array1 is:-  2
Shap of array1 is:-  (4, 5)
Data type of array1 is:-  int32
Total size of array1 is:-  20
Sizeof each element of array1 is:-  4
