## Name: Gopani Kenil G. 
## Roll No: CE049 
## ID: 19CEUOS080
##  Lab-4

### Task 2: 
### Linear regression using PyTorch built-ins

In [1]:
import numpy as np
import torch

In [2]:
# Targets (apples, oranges)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [3]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [4]:
from torch.utils.data import TensorDataset

train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [5]:
from torch.utils.data import DataLoader

batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [6]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 91.,  88.,  64.]])
tensor([[ 56.,  70.],
        [119., 133.],
        [103., 119.],
        [ 22.,  37.],
        [ 81., 101.]])


### nn.Linear

In [7]:
import torch.nn as nn

In [8]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.4006, -0.1266, -0.4798],
        [-0.1107,  0.3044, -0.0431]], requires_grad=True)
Parameter containing:
tensor([-0.4878, -0.5087], requires_grad=True)


In [9]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4006, -0.1266, -0.4798],
         [-0.1107,  0.3044, -0.0431]], requires_grad=True),
 Parameter containing:
 tensor([-0.4878, -0.5087], requires_grad=True)]

In [10]:
preds = model(inputs)
preds

tensor([[-58.8435,   9.9573],
        [-78.7881,  13.4539],
        [-80.1302,  28.1579],
        [-64.5438,  -0.2996],
        [-73.8665,  18.0655]], grad_fn=<AddmmBackward0>)

### loss functions

In [11]:
import torch.nn.functional as F

loss_fn = F.mse_loss

loss = loss_fn(model(inputs), targets)
print(loss)

tensor(15098.6045, grad_fn=<MseLossBackward0>)


### Optimizer

In [12]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

### Train for multiple epochs

In [13]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [14]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 701.5037
Epoch [20/100], Loss: 257.5267
Epoch [30/100], Loss: 224.5612
Epoch [40/100], Loss: 202.3583
Epoch [50/100], Loss: 182.8520
Epoch [60/100], Loss: 165.5914
Epoch [70/100], Loss: 150.3072
Epoch [80/100], Loss: 136.7654
Epoch [90/100], Loss: 124.7593
Epoch [100/100], Loss: 114.1072


In [15]:
prediction = model(inputs)
prediction

tensor([[ 60.6334,  73.0015],
        [ 80.1602,  97.8850],
        [117.7705, 134.9626],
        [ 41.2655,  52.6920],
        [ 86.4864, 105.0446]], grad_fn=<AddmmBackward0>)

In [16]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [17]:
# predict target values based on unkonown values

model(torch.tensor([[75, 63, 44.]]))

tensor([[57.4526, 70.0137]], grad_fn=<AddmmBackward0>)