## Name: Gopani Kenil G. 
## Roll No: CE049 
## ID: 19CEUOS080
##  Lab-4

### Task 1: 
### Linear regression model from scratch

In [ ]:
import numpy as np
import torch

In [ ]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

targets = np.array([[56],[81],[119],[22],[103]], dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
weight = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

In [ ]:
inputs @ weight.t() + bias

tensor([[   5.7145, -141.5049],
        [ -10.8321, -185.2172],
        [ -58.7568, -230.6388],
        [  90.0214, -133.2933],
        [ -65.8789, -180.7875]], grad_fn=<AddBackward0>)

In [ ]:
def model(inputs):
    return inputs @ weight.t() + bias

In [ ]:
prediction = model(inputs)
print(prediction)

tensor([[   5.7145, -141.5049],
        [ -10.8321, -185.2172],
        [ -58.7568, -230.6388],
        [  90.0214, -133.2933],
        [ -65.8789, -180.7875]], grad_fn=<AddBackward0>)


### Loss function

In [ ]:
# calculate loss

def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [ ]:
loss = mse(prediction, targets)
print(loss)

tensor(41248.4727, grad_fn=<DivBackward0>)


### Compute gradients

In [ ]:
loss.backward()
print(weight.grad)
print(bias.grad)

tensor([[ -6441.3740,  -9711.4434,  -5530.8320],
        [-20896.6934, -23486.5527, -14284.1289]])
tensor([ -84.1464, -250.4884])


### Train the model using gradient descent

In [ ]:
for i in range(100):
    prediction = model(inputs)
    loss = mse(prediction, targets)
    loss.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()

In [ ]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(1014.9232, grad_fn=<DivBackward0>)


In [ ]:
prediction

tensor([[ 71.0020,  61.9493],
        [ 82.1882,  84.5428],
        [ 96.4928, 105.6886],
        [ 99.9484,  48.9702],
        [ 55.9880,  89.6744]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])