## Name: Gopani Kenil G. 
## Roll No: CE049 
## ID: 19CEUOS080
##  Lab-11

### Try SVM classifier on MNIST dataset, compare the performance of linear, polynomial and RBF kernels.

In [1]:
import numpy as np
import pandas as pd
from sklearn import svm
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
from tensorflow.keras.datasets import mnist
(features_train, targets_train), (features_test, targets_test) = mnist.load_data()
features_train, features_test = features_train.reshape([-1, 784]), features_test.reshape([-1, 784])
features_train, features_test = features_train / 255., features_test / 255.
print(features_train.shape)
print(features_test.shape)
print(targets_train.shape)
print(targets_test.shape)

(60000, 784)
(10000, 784)
(60000,)
(10000,)


In [3]:
svm_classifier = svm.SVC(kernel='linear')
svm_classifier.fit(features_train[:15000], targets_train[:15000])
prediction = svm_classifier.predict(features_test)
print(prediction)
print("Accuracy - {}%".format(accuracy_score(y_pred=prediction, y_true=targets_test)*100))

[7 2 1 ... 4 5 6]
Accuracy - 92.19000000000001%


In [4]:
svm_classifier = svm.SVC(kernel='poly')
svm_classifier.fit(features_train[:15000], targets_train[:15000])
prediction = svm_classifier.predict(features_test)
print(prediction)
print("Accuracy - {}%".format(accuracy_score(y_pred=prediction, y_true=targets_test)*100))

[7 2 1 ... 4 5 6]
Accuracy - 96.09%


In [5]:
svm_classifier = svm.SVC(kernel='rbf')
svm_classifier.fit(features_train[:15000], targets_train[:15000])
prediction = svm_classifier.predict(features_test)
print(prediction)
print("Accuracy - {}%".format(accuracy_score(y_pred=prediction, y_true=targets_test)*100))

[7 2 1 ... 4 5 6]
Accuracy - 96.67%
