## Name: Gopani Kenil G. 
## Roll No: CE049 
## ID: 19CEUOS080
##  Lab-7

In [18]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
import math
from sklearn.model_selection import train_test_split

In [19]:
data = pd.read_csv('BuyComputer.csv')
data.drop(columns=['User ID',],axis=1,inplace=True)
data

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [20]:
# Scaling data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
transformed_data = sc.fit_transform(data)

In [21]:
transformed_data

array([[-1.78179743, -1.49004624, -0.74593581],
       [-0.25358736, -1.46068138, -0.74593581],
       [-1.11320552, -0.78528968, -0.74593581],
       ...,
       [ 1.17910958, -1.46068138,  1.34059793],
       [-0.15807423, -1.07893824, -0.74593581],
       [ 1.08359645, -0.99084367,  1.34059793]])

In [22]:
# Splitting data

X = transformed_data[:,0:2]
Y = transformed_data[:,2]

Y = [0 if a<0 else 1 for a in Y]
Y = np.array(Y)


X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 49)

In [23]:
# define logistic_regression class

class LogisticRegression:
    
    def __init__(self,lr,epochs=100):
        self.learning_rate = lr
        self.epochs = epochs
        pass
    
    def sigmoid(self,X):
        return 1/(1+np.exp(-((X).dot(self.Weights)+self.Bias)))
    
    def get_loss(self):
        return (np.sum(-1*(self.Y)*np.log(self.sigmoid(self.X))-(1-self.Y)*np.log(1-self.sigmoid(self.X)))/self.Num_samples)
    
    def fit(self,X,Y):
        # Assigning data to X and Y
        self.X = X
        self.Y = Y

        # Computing M -> No of training samples 
        # Computing N -> No of features
        self.Num_samples,self.Num_features = X.shape
        print(self.Num_samples,self.Num_features)

        # Initializing all the weights
        self.Weights = np.zeros(self.Num_features)
        self.Bias = 0
        for i in range(self.epochs):
            print("Epoch ",i)
            
            # Gradient Calculation
            ans = self.sigmoid(self.X)
            t = ( ans - self.Y.T )
            t = np.reshape( t, self.Num_samples ) 
            
            dW = np.dot( self.X.T, t ) / self.Num_samples
            db = np.sum( t ) / self.Num_samples
            
            self.Weights = self.Weights - self.learning_rate * dW    
            self.Bias = self.Bias - self.learning_rate * db
            
            print(self.get_loss())
        return self
  
    # Return predictions based on X
    def predict(self,X):
        ret_val = []
        for dat in self.sigmoid(X):
            ret_val.append(1 if dat>=0.5 else 0)
        return ret_val

In [24]:
lr = LogisticRegression(0.1,400)
lr.fit(X_train,y_train)

320 2
Epoch  0
0.6780875555355753
Epoch  1
0.6638971888497618
Epoch  2
0.6505235916012289
Epoch  3
0.6379161606753214
Epoch  4
0.6260264393030802
Epoch  5
0.6148082954112423
Epoch  6
0.6042180290693592
Epoch  7
0.5942144205398296
Epoch  8
0.584758729979985
Epoch  9
0.5758146589554661
Epoch  10
0.5673482827869974
Epoch  11
0.5593279615123695
Epoch  12
0.5517242360058059
Epoch  13
0.54450971462687
Epoch  14
0.5376589547115402
Epoch  15
0.5311483422888932
Epoch  16
0.5249559726129167
Epoch  17
0.519061533435494
Epoch  18
0.513446192402899
Epoch  19
0.5080924895205863
Epoch  20
0.5029842352850297
Epoch  21
0.4981064148125395
Epoch  22
0.49344509809008913
Epoch  23
0.4889873563203622
Epoch  24
0.4847211842222395
Epoch  25
0.4806354280700599
Epoch  26
0.4767197192030016
Epoch  27
0.4729644127038606
Epoch  28
0.4693605309295806
Epoch  29
0.46589971157024584
Epoch  30
0.4625741599158502
Epoch  31
0.45937660501861954
Epoch  32
0.45630025945114827
Epoch  33
0.45333878237569253
Epoch  34
0.450486

Epoch  312
0.3353047065743408
Epoch  313
0.33526434168336045
Epoch  314
0.3352243271256195
Epoch  315
0.3351846592343149
Epoch  316
0.335145334389315
Epoch  317
0.3351063490164453
Epoch  318
0.3350676995867869
Epoch  319
0.3350293826159872
Epoch  320
0.3349913946635833
Epoch  321
0.33495373233233755
Epoch  322
0.33491639226758496
Epoch  323
0.33487937115659183
Epoch  324
0.3348426657279262
Epoch  325
0.3348062727508393
Epoch  326
0.33477018903465805
Epoch  327
0.3347344114281877
Epoch  328
0.33469893681912594
Epoch  329
0.3346637621334863
Epoch  330
0.33462888433503213
Epoch  331
0.33459430042472027
Epoch  332
0.33456000744015446
Epoch  333
0.3345260024550482
Epoch  334
0.33449228257869673
Epoch  335
0.33445884495545836
Epoch  336
0.3344256867642446
Epoch  337
0.33439280521801873
Epoch  338
0.33436019756330354
Epoch  339
0.3343278610796968
Epoch  340
0.33429579307939555
Epoch  341
0.3342639909067279
Epoch  342
0.33423245193769335
Epoch  343
0.33420117357950985
Epoch  344
0.334170153270

In [25]:
lr.Weights

array([2.09138772, 1.01149355])

In [26]:
def getScore(y_originals,y_pred):
    true = 0
    false = 0
    for i in range(len(y_pred)):
        if y_pred[i]==y_originals[i]:
            true = true + 1
        else:
            false = false + 1
    return true/(true+false)

In [27]:
y_pred = lr.predict(X_test)

In [28]:
getScore(y_test,y_pred)*100

76.25

In [29]:
y_test

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1])

In [30]:
np.array(y_pred)

array([0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1])

In [31]:
# Using sklearn LogisticRegression model

from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(random_state = 49)
LR.fit(X_train,y_train)


LogisticRegression(random_state=49)

In [32]:
y_pred = lr.predict(X_test)

In [33]:
getScore(y_test,y_pred)*100

76.25